-- MySQL Script generated by MySQL Workbench
-- 12/22/14 20:05:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estilo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `artista` VARCHAR(100) NOT NULL,
  `estilo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_musica_estilo_idx` (`estilo_id` ASC),
  CONSTRAINT `fk_musica_estilo`
    FOREIGN KEY (`estilo_id`)
    REFERENCES `mydb`.`estilo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regiao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `regiao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estacao_regiao1_idx` (`regiao_id` ASC),
  CONSTRAINT `fk_estacao_regiao1`
    FOREIGN KEY (`regiao_id`)
    REFERENCES `mydb`.`regiao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`top10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`top10` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NULL,
  `estacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_top10_estacao1_idx` (`estacao_id` ASC),
  CONSTRAINT `fk_top10_estacao1`
    FOREIGN KEY (`estacao_id`)
    REFERENCES `mydb`.`estacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`top10_musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`top10_musica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `musica_id` INT NOT NULL,
  `top10_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_top10_musica_musica1_idx` (`musica_id` ASC),
  INDEX `fk_top10_musica_top101_idx` (`top10_id` ASC),
  CONSTRAINT `fk_top10_musica_musica1`
    FOREIGN KEY (`musica_id`)
    REFERENCES `mydb`.`musica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_top10_musica_top101`
    FOREIGN KEY (`top10_id`)
    REFERENCES `mydb`.`top10` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
