package Entidades;
// Generated Jun 4, 2013 9:45:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String turno;
     private int numPeriodos;
     private String nomeCoordenador;
     private String nome;
     private Set disciplinas = new HashSet(0);
     private Set alunos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(String turno, int numPeriodos, String nomeCoordenador, String nome) {
        this.turno = turno;
        this.numPeriodos = numPeriodos;
        this.nomeCoordenador = nomeCoordenador;
        this.nome = nome;
    }
    public Curso(String turno, int numPeriodos, String nomeCoordenador, String nome, Set disciplinas, Set alunos) {
       this.turno = turno;
       this.numPeriodos = numPeriodos;
       this.nomeCoordenador = nomeCoordenador;
       this.nome = nome;
       this.disciplinas = disciplinas;
       this.alunos = alunos;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public int getNumPeriodos() {
        return this.numPeriodos;
    }
    
    public void setNumPeriodos(int numPeriodos) {
        this.numPeriodos = numPeriodos;
    }
    public String getNomeCoordenador() {
        return this.nomeCoordenador;
    }
    
    public void setNomeCoordenador(String nomeCoordenador) {
        this.nomeCoordenador = nomeCoordenador;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }
    public Set getAlunos() {
        return this.alunos;
    }
    
    public void setAlunos(Set alunos) {
        this.alunos = alunos;
    }




}


