package Entidades;
// Generated Jun 4, 2013 9:45:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer matricula;
     private String nome;
     private float salario;
     private Set disciplinas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(String nome, float salario) {
        this.nome = nome;
        this.salario = salario;
    }
    public Professor(String nome, float salario, Set disciplinas) {
       this.nome = nome;
       this.salario = salario;
       this.disciplinas = disciplinas;
    }
   
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public float getSalario() {
        return this.salario;
    }
    
    public void setSalario(float salario) {
        this.salario = salario;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }




}


