package ObjetosDTO;
// Generated Jun 4, 2013 9:45:51 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer idDisciplina;
     private Professor professor;
     private String nomeDisciplina;
     private int cargaHoraria;
//     private Set cursos = new HashSet(0);
//     private Set alunos = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(Professor professor, String nomeDisciplina, int cargaHoraria) {
        this.professor = professor;
        this.nomeDisciplina = nomeDisciplina;
        this.cargaHoraria = cargaHoraria;
    }
//    public Disciplina(Professor professor, String nomeDisciplina, int cargaHoraria, Set cursos, Set alunos) {
//       this.professor = professor;
//       this.nomeDisciplina = nomeDisciplina;
//       this.cargaHoraria = cargaHoraria;
//       this.cursos = cursos;
//       this.alunos = alunos;
//    }
   
    public Integer getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(Integer idDisciplina) {
        this.idDisciplina = idDisciplina;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public String getNomeDisciplina() {
        return this.nomeDisciplina;
    }
    
    public void setNomeDisciplina(String nomeDisciplina) {
        this.nomeDisciplina = nomeDisciplina;
    }
    public int getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(int cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
//    public Set getCursos() {
//        return this.cursos;
//    }
//    
//    public void setCursos(Set cursos) {
//        this.cursos = cursos;
//    }
//    public Set getAlunos() {
//        return this.alunos;
//    }
//    
//    public void setAlunos(Set alunos) {
//        this.alunos = alunos;
//    }




}


